<a href="https://colab.research.google.com/github/Vanitha-Jain/capstone/blob/Feature-selection/Estate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
data=pd.read_csv('/content/EState.csv')
data

,Name,EStateFP1,EStateFP2,EStateFP3,EStateFP4,EStateFP5,EStateFP6,EStateFP7,EStateFP8,EStateFP9,...,EStateFP71,EStateFP72,EStateFP73,EStateFP74,EStateFP75,EStateFP76,EStateFP77,EStateFP78,EStateFP79,bioactivity_class
0,CHEMBL167155,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,inactive
1,CHEMBL166740,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,inactive
2,CHEMBL165038,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,inactive
3,CHEMBL435857,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,inactive
4,CHEMBL352783,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,inactive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1224,CHEMBL5429863,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,inactive
1225,CHEMBL5436920,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,inactive
1226,CHEMBL5405698,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,inactive
1227,CHEMBL5416562,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,inactive
1228,CHEMBL165,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,inactive

In [ ]:
data.dtypes

Name                 object
EStateFP1             int64
EStateFP2             int64
EStateFP3             int64
EStateFP4             int64
                      ...
EStateFP76            int64
EStateFP77            int64
EStateFP78            int64
EStateFP79            int64
bioactivity_class    object
Length: 81, dtype: object

In [ ]:
data['bioactivity_class'].replace('active', 'P', inplace=True)
data['bioactivity_class'].replace('inactive', 'N', inplace=True)
data.rename(columns = {"bioactivity_class": "class"}, inplace = True)
data

<ipython-input-22-d75cbf56e791>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['bioactivity_class'].replace('active', 'P', inplace=True)
<ipython-input-22-d75cbf56e791>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['bioactivity_class'].replace('inactive', 'N', inplace=True)

,Name,EStateFP1,EStateFP2,EStateFP3,EStateFP4,EStateFP5,EStateFP6,EStateFP7,EStateFP8,EStateFP9,...,EStateFP71,EStateFP72,EStateFP73,EStateFP74,EStateFP75,EStateFP76,EStateFP77,EStateFP78,EStateFP79,class
0,CHEMBL167155,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,N
1,CHEMBL166740,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,N
2,CHEMBL165038,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,N
3,CHEMBL435857,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,N
4,CHEMBL352783,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1224,CHEMBL5429863,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,N
1225,CHEMBL5436920,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,N
1226,CHEMBL5405698,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,N
1227,CHEMBL5416562,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,N
1228,CHEMBL165,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,N

In [ ]:
data.isnull().sum().sum()

0

In [ ]:
data.dropna(inplace =True)
data.isnull().sum().sum()

0

In [ ]:
data1 = data.iloc[:,1:80]
data1
data2 = data.iloc[:,-1]

In [ ]:
data1
data2

0       N
1       N
2       N
3       N
4       N
       ..
1224    N
1225    N
1226    N
1227    N
1228    N
Name: class, Length: 1229, dtype: object

In [ ]:
from sklearn.feature_selection import VarianceThreshold
threshold = VarianceThreshold(threshold=.1)
def variance_threshold_selector(data1, threshold=0.10):
    selector = VarianceThreshold(threshold)
    selector.fit(data1)
    return data[data1.columns[selector.get_support(indices=True)]]
data1_HV = variance_threshold_selector(data1)

In [ ]:
data1_HV = variance_threshold_selector(data1)
data1_HV

,EStateFP7,EStateFP9,EStateFP11,EStateFP13,EStateFP15,EStateFP16,EStateFP18,EStateFP19,EStateFP24,EStateFP29,EStateFP30,EStateFP32,EStateFP34,EStateFP35,EStateFP36,EStateFP38,EStateFP53,EStateFP54
0,1,0,0,0,0,1,1,0,1,0,0,0,1,1,0,0,1,0
1,1,0,0,0,0,1,1,0,1,0,0,0,1,1,0,0,1,0
2,1,0,0,0,0,1,1,0,1,0,0,0,1,1,0,0,1,1
3,1,0,0,0,0,1,1,0,1,0,0,0,1,1,0,0,1,1
4,1,0,0,0,0,1,1,0,1,0,0,0,1,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1224,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0
1225,0,0,1,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0
1226,0,0,1,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0
1227,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0
1228,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0

In [ ]:
data2_HV = pd.merge(data1_HV,data2,left_index=True,right_index=True)
data2_HV

,EStateFP7,EStateFP9,EStateFP11,EStateFP13,EStateFP15,EStateFP16,EStateFP18,EStateFP19,EStateFP24,EStateFP29,EStateFP30,EStateFP32,EStateFP34,EStateFP35,EStateFP36,EStateFP38,EStateFP53,EStateFP54,class
0,1,0,0,0,0,1,1,0,1,0,0,0,1,1,0,0,1,0,N
1,1,0,0,0,0,1,1,0,1,0,0,0,1,1,0,0,1,0,N
2,1,0,0,0,0,1,1,0,1,0,0,0,1,1,0,0,1,1,N
3,1,0,0,0,0,1,1,0,1,0,0,0,1,1,0,0,1,1,N
4,1,0,0,0,0,1,1,0,1,0,0,0,1,1,0,0,1,0,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1224,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,N
1225,0,0,1,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,N
1226,0,0,1,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,N
1227,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,N
1228,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,N

In [ ]:
## remove features that display high correlation with many other features
correlated_features_1 = set()
corr_matrix_class = data2_HV.corr(numeric_only=True)


for i in range(len(corr_matrix_class.columns)):
    for j in range(i):
        if abs(corr_matrix_class.iloc[i, j]) > 0.7:
            colname = corr_matrix_class.columns[i]
            correlated_features_1.add(colname)
correlated_features_1

{'EStateFP35'}

In [ ]:
def remove_correlated_features(features, data):
    for x in features:
        data.drop(x, axis=1, inplace=True)
    return data

In [ ]:
data3= remove_correlated_features(correlated_features_1, data2_HV)
data3

,EStateFP7,EStateFP9,EStateFP11,EStateFP13,EStateFP15,EStateFP16,EStateFP18,EStateFP19,EStateFP24,EStateFP29,EStateFP30,EStateFP32,EStateFP34,EStateFP36,EStateFP38,EStateFP53,EStateFP54,class
0,1,0,0,0,0,1,1,0,1,0,0,0,1,0,0,1,0,N
1,1,0,0,0,0,1,1,0,1,0,0,0,1,0,0,1,0,N
2,1,0,0,0,0,1,1,0,1,0,0,0,1,0,0,1,1,N
3,1,0,0,0,0,1,1,0,1,0,0,0,1,0,0,1,1,N
4,1,0,0,0,0,1,1,0,1,0,0,0,1,0,0,1,0,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1224,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,N
1225,0,0,1,0,1,0,1,0,0,1,0,0,0,0,0,0,0,N
1226,0,0,1,0,1,0,1,0,0,1,0,0,0,0,0,0,0,N
1227,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,N
1228,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,N

In [ ]:
data3.to_csv('Estate2.csv')

In [ ]:
X = data3.iloc[:,1:17]  #independent columns
X
y = data3.iloc[:,-1]
y   #target column i.e price range

0       N
1       N
2       N
3       N
4       N
       ..
1224    N
1225    N
1226    N
1227    N
1228    N
Name: class, Length: 1229, dtype: object

In [ ]:
X

,EStateFP9,EStateFP11,EStateFP13,EStateFP15,EStateFP16,EStateFP18,EStateFP19,EStateFP24,EStateFP29,EStateFP30,EStateFP32,EStateFP34,EStateFP36,EStateFP38,EStateFP53,EStateFP54
0,0,0,0,0,1,1,0,1,0,0,0,1,0,0,1,0
1,0,0,0,0,1,1,0,1,0,0,0,1,0,0,1,0
2,0,0,0,0,1,1,0,1,0,0,0,1,0,0,1,1
3,0,0,0,0,1,1,0,1,0,0,0,1,0,0,1,1
4,0,0,0,0,1,1,0,1,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1224,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0
1225,0,1,0,1,0,1,0,0,1,0,0,0,0,0,0,0
1226,0,1,0,1,0,1,0,0,1,0,0,0,0,0,0,0
1227,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0
1228,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0

In [ ]:
from sklearn.preprocessing import StandardScaler
# y = data['class']
# X_features =data.drop(columns='class')
scaler = StandardScaler()
X_transform = scaler.fit_transform(X)
X_transform_pd = pd.DataFrame(X_transform, columns = X.columns)
X_transform_pd

# #Standardize/normalize the data
# from sklearn.preprocessing import MinMaxScaler
# sc = MinMaxScaler()
# X_transform = sc.fit_transform(X)
# X_transform

,EStateFP9,EStateFP11,EStateFP13,EStateFP15,EStateFP16,EStateFP18,EStateFP19,EStateFP24,EStateFP29,EStateFP30,EStateFP32,EStateFP34,EStateFP36,EStateFP38,EStateFP53,EStateFP54
0,-2.309773,-0.788272,-0.948439,-0.375676,0.677953,0.931548,-0.57829,1.098391,-1.169622,-0.83377,-0.625976,1.426383,-1.332016,-0.484949,2.692271,-0.403391
1,-2.309773,-0.788272,-0.948439,-0.375676,0.677953,0.931548,-0.57829,1.098391,-1.169622,-0.83377,-0.625976,1.426383,-1.332016,-0.484949,2.692271,-0.403391
2,-2.309773,-0.788272,-0.948439,-0.375676,0.677953,0.931548,-0.57829,1.098391,-1.169622,-0.83377,-0.625976,1.426383,-1.332016,-0.484949,2.692271,2.478981
3,-2.309773,-0.788272,-0.948439,-0.375676,0.677953,0.931548,-0.57829,1.098391,-1.169622,-0.83377,-0.625976,1.426383,-1.332016,-0.484949,2.692271,2.478981
4,-2.309773,-0.788272,-0.948439,-0.375676,0.677953,0.931548,-0.57829,1.098391,-1.169622,-0.83377,-0.625976,1.426383,-1.332016,-0.484949,2.692271,-0.403391
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1224,-2.309773,1.268598,-0.948439,-0.375676,-1.475029,0.931548,-0.57829,-0.910422,0.854977,-0.83377,-0.625976,-0.701074,-1.332016,-0.484949,-0.371434,-0.403391
1225,-2.309773,1.268598,-0.948439,2.661865,-1.475029,0.931548,-0.57829,-0.910422,0.854977,-0.83377,-0.625976,-0.701074,-1.332016,-0.484949,-0.371434,-0.403391
1226,-2.309773,1.268598,-0.948439,2.661865,-1.475029,0.931548,-0.57829,-0.910422,0.854977,-0.83377,-0.625976,-0.701074,-1.332016,-0.484949,-0.371434,-0.403391
1227,-2.309773,1.268598,-0.948439,-0.375676,-1.475029,0.931548,-0.57829,-0.910422,0.854977,-0.83377,-0.625976,-0.701074,-1.332016,-0.484949,-0.371434,-0.403391
1228,-2.309773,1.268598,-0.948439,-0.375676,-1.475029,-1.073482,-0.57829,-0.910422,-1.169622,-0.83377,-0.625976,1.426383,-1.332016,-0.484949,-0.371434,-0.403391

In [ ]:
## Split data into train and test sets.
from sklearn.model_selection import train_test_split
seed_num = 10
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.3, random_state=seed_num)

print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(860, 16)
(860,)
(369, 16)
(369,)

In [ ]:
X_train

,EStateFP9,EStateFP11,EStateFP13,EStateFP15,EStateFP16,EStateFP18,EStateFP19,EStateFP24,EStateFP29,EStateFP30,EStateFP32,EStateFP34,EStateFP36,EStateFP38,EStateFP53,EStateFP54
387,1,1,0,0,0,1,0,1,1,0,0,0,0,0,0,0
250,0,0,1,1,0,1,1,1,1,0,1,0,0,1,1,0
378,1,1,1,0,1,1,0,1,1,0,1,1,1,0,0,1
73,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0
1185,1,0,1,0,1,1,0,1,1,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
733,1,1,1,0,1,0,0,0,0,1,0,0,1,0,0,0
1180,1,1,1,0,1,1,0,1,1,1,0,0,1,0,0,1
1147,1,0,1,0,1,0,1,0,0,1,0,0,1,1,0,0
527,1,0,0,0,0,1,0,0,1,1,1,0,0,0,1,0
1149,1,1,0,0,1,0,0,1,0,0,0,0,1,0,0,0

In [ ]:
y_train

387     N
250     N
378     N
73      N
1185    P
       ..
733     N
1180    P
1147    N
527     P
1149    P
Name: class, Length: 860, dtype: object

In [ ]:
Training_set  = pd.concat([X_train,y_train],axis=1)
Training_set

,EStateFP9,EStateFP11,EStateFP13,EStateFP15,EStateFP16,EStateFP18,EStateFP19,EStateFP24,EStateFP29,EStateFP30,EStateFP32,EStateFP34,EStateFP36,EStateFP38,EStateFP53,EStateFP54,class
387,1,1,0,0,0,1,0,1,1,0,0,0,0,0,0,0,N
250,0,0,1,1,0,1,1,1,1,0,1,0,0,1,1,0,N
378,1,1,1,0,1,1,0,1,1,0,1,1,1,0,0,1,N
73,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,N
1185,1,0,1,0,1,1,0,1,1,0,0,0,1,0,0,1,P
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
733,1,1,1,0,1,0,0,0,0,1,0,0,1,0,0,0,N
1180,1,1,1,0,1,1,0,1,1,1,0,0,1,0,0,1,P
1147,1,0,1,0,1,0,1,0,0,1,0,0,1,1,0,0,N
527,1,0,0,0,0,1,0,0,1,1,1,0,0,0,1,0,P
1149,1,1,0,0,1,0,0,1,0,0,0,0,1,0,0,0,P

In [ ]:
Training_set.to_csv('Estate_Training_set.csv')

In [ ]:
Testing_set  = pd.concat([X_test,y_test],axis=1)
Testing_set

,EStateFP9,EStateFP11,EStateFP13,EStateFP15,EStateFP16,EStateFP18,EStateFP19,EStateFP24,EStateFP29,EStateFP30,EStateFP32,EStateFP34,EStateFP36,EStateFP38,EStateFP53,EStateFP54,class
693,1,0,1,0,1,0,0,0,1,0,0,1,1,0,0,0,N
834,1,0,0,0,0,1,0,0,1,0,1,0,1,0,0,0,N
1016,0,1,0,0,1,1,0,1,1,0,0,0,1,0,0,0,P
1113,1,1,1,0,1,0,0,0,0,0,0,0,1,0,0,0,P
31,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,P
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1102,1,0,0,0,0,1,0,1,1,1,1,0,0,1,1,0,P
909,1,1,1,1,1,0,0,1,1,1,0,0,1,0,0,0,P
270,1,0,1,1,0,1,1,1,1,0,1,0,0,1,1,0,N
349,1,0,1,0,1,0,1,1,0,1,0,1,1,0,0,0,P
1,0,0,0,0,1,1,0,1,0,0,0,1,0,0,1,0,N

In [ ]:
Testing_set.to_csv('Estate_Testing_set.csv')

In [ ]:
from sklearn.feature_selection import SelectKBest, mutual_info_classif
kBest = SelectKBest(mutual_info_classif, k = 15)
X_kBestFeatures = kBest.fit_transform(X_train, y_train)
X_kBestFeatures.shape

(860, 15)

In [ ]:
kBest.get_support(True)

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
X_kBestFeatures = Training_set.iloc[:, kBest.get_support(True)]
X_kBestFeatures.columns

Index(['EStateFP9', 'EStateFP13', 'EStateFP15', 'EStateFP16', 'EStateFP18',
       'EStateFP19', 'EStateFP24', 'EStateFP29', 'EStateFP30', 'EStateFP32',
       'EStateFP34', 'EStateFP36', 'EStateFP38', 'EStateFP53', 'EStateFP54'],
      dtype='object')

In [ ]:
f = kBest.get_support(1)
X_new = X_train[X_train.columns[f]]
X_new
data_scores = pd.DataFrame(kBest.scores_)
data_columns = pd.DataFrame(X.columns)

In [ ]:
#Concat two dataframes for better visualization
featureScores = pd.concat([data_columns, data_scores], axis = 1)

#naming the dataframe columns
featureScores.columns = ['Features', 'Scores']
featureScores

      Features    Scores
0    EStateFP9  0.053531
1   EStateFP11  0.000000
2   EStateFP13  0.000000
3   EStateFP15  0.000000
4   EStateFP16  0.009527
5   EStateFP18  0.026409
6   EStateFP19  0.010241
7   EStateFP24  0.000000
8   EStateFP29  0.000000
9   EStateFP30  0.038623
10  EStateFP32  0.023073
11  EStateFP34  0.000000
12  EStateFP36  0.008181
13  EStateFP38  0.000000
14  EStateFP53  0.007410
15  EStateFP54  0.013515

In [ ]:
#Print top 25 best features
print(featureScores.nlargest(15, 'Scores'))

      Features    Scores
0    EStateFP9  0.053531
9   EStateFP30  0.038623
5   EStateFP18  0.026409
10  EStateFP32  0.023073
15  EStateFP54  0.013515
6   EStateFP19  0.010241
4   EStateFP16  0.009527
12  EStateFP36  0.008181
14  EStateFP53  0.007410
1   EStateFP11  0.000000
2   EStateFP13  0.000000
3   EStateFP15  0.000000
7   EStateFP24  0.000000
8   EStateFP29  0.000000
11  EStateFP34  0.000000

In [ ]:
Graph = (featureScores.nlargest(15, 'Scores'))
Graph

      Features    Scores
0    EStateFP9  0.053531
9   EStateFP30  0.038623
5   EStateFP18  0.026409
10  EStateFP32  0.023073
15  EStateFP54  0.013515
6   EStateFP19  0.010241
4   EStateFP16  0.009527
12  EStateFP36  0.008181
14  EStateFP53  0.007410
1   EStateFP11  0.000000
2   EStateFP13  0.000000
3   EStateFP15  0.000000
7   EStateFP24  0.000000
8   EStateFP29  0.000000
11  EStateFP34  0.000000

In [ ]:
Graph.to_csv('Estate_Features.csv')

In [ ]:
import matplotlib.pyplot as plt
data = pd.read_csv('Estate_Features.csv')
df = pd.DataFrame(data)
X = list(df.iloc[:, 1])
Y = list(df.iloc[:, 2])
plt.bar(X, Y, color='c')
plt.title("Estate_Feature_importance", fontweight="bold")
plt.xlabel("Features", fontweight = 'bold')
plt.ylabel("Scores", fontweight = 'bold')
plt.xticks(rotation = 80, fontweight="bold")
plt.yticks(fontweight="bold")
fig = plt.figure(figsize=(10, 10))
plt.savefig("Features.jpg", bbox_inches = 'tight')

NameError: name 'pd' is not defined

In [ ]:
Trainset = pd.concat([X_new,y_train],axis=1)
Trainset

,EStateFP9,EStateFP13,EStateFP15,EStateFP16,EStateFP18,EStateFP19,EStateFP24,EStateFP29,EStateFP30,EStateFP32,EStateFP34,EStateFP36,EStateFP38,EStateFP53,EStateFP54,class
387,1,0,0,0,1,0,1,1,0,0,0,0,0,0,0,N
250,0,1,1,0,1,1,1,1,0,1,0,0,1,1,0,N
378,1,1,0,1,1,0,1,1,0,1,1,1,0,0,1,N
73,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,N
1185,1,1,0,1,1,0,1,1,0,0,0,1,0,0,1,P
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
733,1,1,0,1,0,0,0,0,1,0,0,1,0,0,0,N
1180,1,1,0,1,1,0,1,1,1,0,0,1,0,0,1,P
1147,1,1,0,1,0,1,0,0,1,0,0,1,1,0,0,N
527,1,0,0,0,1,0,0,1,1,1,0,0,0,1,0,P
1149,1,0,0,1,0,0,1,0,0,0,0,1,0,0,0,P

In [ ]:
f = kBest.get_support(1)
Test_new = X_test[X_test.columns[f]]
Test_new

,EStateFP9,EStateFP13,EStateFP15,EStateFP16,EStateFP18,EStateFP19,EStateFP24,EStateFP29,EStateFP30,EStateFP32,EStateFP34,EStateFP36,EStateFP38,EStateFP53,EStateFP54
693,1,1,0,1,0,0,0,1,0,0,1,1,0,0,0
834,1,0,0,0,1,0,0,1,0,1,0,1,0,0,0
1016,0,0,0,1,1,0,1,1,0,0,0,1,0,0,0
1113,1,1,0,1,0,0,0,0,0,0,0,1,0,0,0
31,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1102,1,0,0,0,1,0,1,1,1,1,0,0,1,1,0
909,1,1,1,1,0,0,1,1,1,0,0,1,0,0,0
270,1,1,1,0,1,1,1,1,0,1,0,0,1,1,0
349,1,1,0,1,0,1,1,0,1,0,1,1,0,0,0
1,0,0,0,1,1,0,1,0,0,0,1,0,0,1,0

In [ ]:
Testset = pd.concat([Test_new,y_test],axis=1)
Testset

,EStateFP9,EStateFP13,EStateFP15,EStateFP16,EStateFP18,EStateFP19,EStateFP24,EStateFP29,EStateFP30,EStateFP32,EStateFP34,EStateFP36,EStateFP38,EStateFP53,EStateFP54,class
693,1,1,0,1,0,0,0,1,0,0,1,1,0,0,0,N
834,1,0,0,0,1,0,0,1,0,1,0,1,0,0,0,N
1016,0,0,0,1,1,0,1,1,0,0,0,1,0,0,0,P
1113,1,1,0,1,0,0,0,0,0,0,0,1,0,0,0,P
31,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,P
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1102,1,0,0,0,1,0,1,1,1,1,0,0,1,1,0,P
909,1,1,1,1,0,0,1,1,1,0,0,1,0,0,0,P
270,1,1,1,0,1,1,1,1,0,1,0,0,1,1,0,N
349,1,1,0,1,0,1,1,0,1,0,1,1,0,0,0,P
1,0,0,0,1,1,0,1,0,0,0,1,0,0,1,0,N

In [ ]:
Trainset.to_csv('Trainset_Estate_after_feature.csv')
Testset.to_csv('Testset_Estate_after_feature.csv')

In [ ]:
Trainset['class'].replace('N', 0, inplace=True)
Trainset['class'].replace('P', 1, inplace=True)
Trainset.rename(columns = {"class": "class"}, inplace = True)
Trainset

<ipython-input-57-e976ed617192>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Trainset['class'].replace('N', 0, inplace=True)
<ipython-input-57-e976ed617192>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Trainset['class'].replace('P', 1, inplace=True)
<ipython-input-57-e976ed617192>:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  Trainset['class'].replace('P', 1, inplace=True)

,EStateFP9,EStateFP13,EStateFP15,EStateFP16,EStateFP18,EStateFP19,EStateFP24,EStateFP29,EStateFP30,EStateFP32,EStateFP34,EStateFP36,EStateFP38,EStateFP53,EStateFP54,class
387,1,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0
250,0,1,1,0,1,1,1,1,0,1,0,0,1,1,0,0
378,1,1,0,1,1,0,1,1,0,1,1,1,0,0,1,0
73,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0
1185,1,1,0,1,1,0,1,1,0,0,0,1,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
733,1,1,0,1,0,0,0,0,1,0,0,1,0,0,0,0
1180,1,1,0,1,1,0,1,1,1,0,0,1,0,0,1,1
1147,1,1,0,1,0,1,0,0,1,0,0,1,1,0,0,0
527,1,0,0,0,1,0,0,1,1,1,0,0,0,1,0,1
1149,1,0,0,1,0,0,1,0,0,0,0,1,0,0,0,1

In [ ]:
Testset['class'].replace('N', 0, inplace=True)
Testset['class'].replace('P', 1, inplace=True)
Testset.rename(columns = {"class": "class"}, inplace = True)
Testset.head()

<ipython-input-58-c538cf0d9b31>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Testset['class'].replace('N', 0, inplace=True)
<ipython-input-58-c538cf0d9b31>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Testset['class'].replace('P', 1, inplace=True)
<ipython-input-58-c538cf0d9b31>:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  Testset['class'].replace('P', 1, inplace=True)

,EStateFP9,EStateFP13,EStateFP15,EStateFP16,EStateFP18,EStateFP19,EStateFP24,EStateFP29,EStateFP30,EStateFP32,EStateFP34,EStateFP36,EStateFP38,EStateFP53,EStateFP54,class
693,1,1,0,1,0,0,0,1,0,0,1,1,0,0,0,0
834,1,0,0,0,1,0,0,1,0,1,0,1,0,0,0,0
1016,0,0,0,1,1,0,1,1,0,0,0,1,0,0,0,1
1113,1,1,0,1,0,0,0,0,0,0,0,1,0,0,0,1
31,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,1

In [ ]:
Trainset.to_csv('Trainset1_Estate_after_feature.csv')
Testset.to_csv('Testset1_Estate_after_feature.csv')